Created Base File
ShingekiNoChikungunya/netmqtt pull request #1
Opened 2020-02-20 01:10 UTC by RafaBonin

Created a Base File for connecting, receiving data, parsing data and sending data

2020-02-20 01:15 UTC, olivatooo requested changes

2020-02-20 01:15 UTC, olivatooo commented on netmosquito.py
> +host='127.0.0.1' #Host IP goes here
Maybe we can receive this with arguments?

2020-02-20 01:15 UTC, olivatooo commented on netmosquito.py
> +def recieve_data(s):
This function does not receive any data < 2048. This needs a better receive function

2020-02-20 01:15 UTC, olivatooo commented on netmosquito.py
> +def recieve_data(s):
mispelled `receive`

2020-02-20 01:15 UTC, olivatooo commented on netmosquito.py
> +def parse_data(raw_data):
This always returns None

2020-02-20 01:15 UTC, olivatooo commented on netmosquito.py
> +def send_data(parsed_data):
`s` is global, maybe specify this, or send socket as a param

2020-02-20 01:15 UTC, olivatooo commented on netmosquito.py
> +while True:
We need a better condition! While True is not good at all

2020-02-20 01:15 UTC, olivatooo commented on netmosquito.py
> +	send_data(parsed_data)
Missing blank line at the end of file

2020-02-20 02:03 UTC, olivatooo requested changes

2020-02-20 02:03 UTC, olivatooo commented on netmosquito.py
> +try:
Don't make this check with try catch, and display a usage of the program with an example

2020-02-20 02:03 UTC, olivatooo commented on netmosquito.py
> +		data+=s.recv(2048).decode()
Too big, put 4 bytes or less!

2020-02-20 02:03 UTC, olivatooo commented on netmosquito.py
> +	while True:
fix this condition

2020-02-21 01:27 UTC, olivatooo requested changes
Apply pep-8 to file, separate all socket functions into another file and only import here

2020-02-21 01:27 UTC, olivatooo commented on netmosquito.py
> +buffer_size = 1				#How much data would you like to receive at once (bytes)
Unaligned commentary

2020-02-21 01:27 UTC, olivatooo commented on netmosquito.py
> +timeout_time= 2				#Timeout to not keep holding forever in case of incomplete packet
Unaligned commentary

2020-02-21 01:27 UTC, olivatooo commented on netmosquito.py
> +	host=sys.argv[1] 		#Host IP goes here
Unaligned commentary

2020-02-21 01:27 UTC, olivatooo commented on netmosquito.py
> +	port=int(sys.argv[2]) 	#Port Goes Here
Unaligned commentary

2020-02-21 01:27 UTC, olivatooo commented on netmosquito.py
> +	print(('Error while running, please execute proggram as following:\npython netmosquito.py <host> <port>'))
Double `( )`

2020-02-21 01:27 UTC, olivatooo commented on netmosquito.py
> +s.settimeout(timeout_time)	#Sets the timeout time
Unaligned commentary

2020-02-21 01:27 UTC, olivatooo commented on netmosquito.py
> +	#This functions recieves data in n bytes chunks until '\n' is received or timeout ocurrs
Commentary in function without [doc string](https://www.askpython.com/python/python-comments)

2020-02-21 01:27 UTC, olivatooo commented on netmosquito.py
> +	#This functions recieves data in n bytes chunks until '\n' is received or timeout ocurrs
Unaligned commentary

2020-02-21 01:27 UTC, olivatooo commented on netmosquito.py
> +	try:					#Prevents exception from timeouts
Unaligned commentary

2020-02-21 01:27 UTC, olivatooo commented on netmosquito.py
> +		try:					#Prevents exception from timeouts
Unaligned commentary

2020-02-21 01:27 UTC, olivatooo commented on netmosquito.py
> +if len(sys.argv)==3:
Put this initial check into a function

2020-02-29 02:07 UTC, olivatooo approved these changes
mano, dá play, se der ruim amanhã já sabe que o piriquito vai cantar

2020-03-02 01:43 UTC, sugayaa approved these changes

2020-03-08 12:57 UTC, merged